### ISSUE TITLE
Commands and others are not shown in floating windows.

### ISSUE THREAD

**Issue by mariochavez** [weizheheng/ror.nvim#22]
Hi,

First, thanks for this plugin, it is great!

I have just installed with Neovim 0.9, and I did notice from your videos that commands output are not being shown in floating windows but at the bottom of the editor.
I'm uncertain if this is an issue with Neovim 0.9 or if it's something that I'm missing setting up the plugin.

![Screenshot 2023-04-26 at 12 41 51](https://user-images.githubusercontent.com/59967/234676179-4b2952c5-ae7d-45aa-bdad-f04ed84a4ab3.png)

**Comment by weizheheng** [comment]
@mariochavez Thanks for trying it out. Ahh, I believe that is because I have the [dressing plugin](https://github.com/stevearc/dressing.nvim) installed which "beautify" the default `vim.ui.select` and `vim.ui.input`. I have added them to the README under [optional dependencies](https://github.com/weizheheng/ror.nvim#optional-dependencies).

If you don't mind installing the plugin, after installing it you should be able to list them in the floating window.

**Comment by mariochavez** [comment]
Ohh, thanks for the plugin, very helpful.
